name: "Publish Zdk.Utilities.Authentication to Github packages"

on:
  push:
    tags:
    - 'v*'

env:
  PROJECT_PATH: 'Zdk.Utilities.Authentication/Zdk.Utilities.Authentication.csproj'
  OUTPUT_DIR: '${{ github.workspace }}/output'
  SOURCE_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: Version
      id: version
      uses: battila7/get-version-action@v2

    - name: Pack
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.OUTPUT_DIR }}

    - name: Authenticate
      run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.PAT }} --store-password-in-clear-text --name github ${{ env.SOURCE_URL }}

    - name: Push
      run: dotnet nuget push ${{ env.OUTPUT_DIR }}/*.nupkg --source github
